#!/bin/sh

if [ -x "$(command -v stack)" ]; then
  stack run
elif [ -x "$(command -v cabal)" ]; then
  cabal build && cabal exec learn-you-a-haskell
else
  >&2 echo "Neither Stack or Cabal are installed, please install at least one of them"
  exit 1
fi
